#!/usr/bin/env Rscript
suppressWarnings(suppressMessages({ }))

need <- function(pkgs){
  for(p in pkgs){
    if(!requireNamespace(p, quietly=TRUE)){
      try(install.packages(p, repos="https://cloud.r-project.org"), silent=TRUE)
    }
  }
}

# --- colorblind-safe palette (Okabe-Ito) ---
okabe <- c(ACF="#D55E00", Normal="#0072B2", Unknown="#999999")

# --- args ---
args <- commandArgs(trailingOnly=TRUE)
opt <- list()
if(length(args)>0){
  for(i in seq(1,length(args),by=2)){
    key <- gsub("^--","",args[i]); val <- if(i+1<=length(args)) args[i+1] else ""
    opt[[key]] <- val
  }
}
counts_path <- opt[["counts"]]
meta_path   <- opt[["meta"]]
outdir      <- if(!is.null(opt[["outdir"]])) opt[["outdir"]] else "results/figures/main"
prefix      <- if(!is.null(opt[["prefix"]])) opt[["prefix"]] else format(Sys.time(), "%Y%m%d_acf")
subset_comp <- if(!is.null(opt[["subset"]])) opt[["subset"]] else "ALL"  # Epithelial / Stromal / ALL

dir.create(outdir, recursive=TRUE, showWarnings=FALSE)
dir.create("results/tables", recursive=TRUE, showWarnings=FALSE)

read_counts_csv <- function(p){
  x <- read.csv(p, check.names=FALSE, stringsAsFactors=FALSE)
  if(ncol(x)>1 && !is.numeric(x[[1]])){ rn <- x[[1]]; x <- x[,-1,drop=FALSE]; rownames(x) <- rn }
  x
}

# --- auto-pick counts if not provided ---
if(is.null(counts_path) || counts_path=="" || !file.exists(counts_path)){
  cands <- list.files("data/processed/acf/normalized", pattern="(?i)\\.csv$", full.names=TRUE)
  if(length(cands)==0) stop("No normalized CSV under data/processed/acf/normalized")
  counts_path <- cands[1]
}

# --- load counts ---
counts <- read_counts_csv(counts_path)
counts[] <- lapply(counts, function(v) suppressWarnings(as.numeric(v)))
counts <- as.matrix(counts)
counts <- counts[rowSums(is.finite(counts))>0,, drop=FALSE]

# --- metadata ---
if(!is.null(meta_path) && file.exists(meta_path)){
  meta <- read.csv(meta_path, stringsAsFactors=FALSE, check.names=FALSE)
  cs <- tolower(colnames(meta))
  if(!"sample" %in% cs) stop("metadata CSV must have a 'sample' column")
  rownames(meta) <- meta[[which(cs=="sample")]]
} else {
  # minimal autogenerated meta if none exists
  samples <- colnames(counts)
  infer <- function(s,re) grepl(re, s, ignore.case=TRUE)
  condition  <- ifelse(infer(samples,"ACF"), "ACF",
                  ifelse(infer(samples,"Norm|Normal|Ctrl|Control"), "Normal","Unknown"))
  compartment <- ifelse(infer(samples,"epi|epith"), "Epithelial",
                   ifelse(infer(samples,"str|stro|stroma"), "Stromal","Unknown"))
  meta <- data.frame(sample=samples, condition=condition, compartment=compartment,
                     stringsAsFactors=FALSE, row.names=samples)
}

# --- harmonize a possible 'Tissue' column to 'compartment' ---
if("Tissue" %in% colnames(meta) && !"compartment" %in% colnames(meta)){
  meta$compartment <- meta$Tissue
}

# --- align & optional subset by compartment ---
common <- intersect(colnames(counts), rownames(meta))
if(length(common) < 3) stop("Not enough overlapping samples between counts and metadata.")
counts <- counts[, common, drop=FALSE]
meta   <- meta[common, , drop=FALSE]

if(!"condition" %in% names(meta))   meta$condition <- "Unknown"
if(!"compartment" %in% names(meta)) meta$compartment <- "Unknown"
meta$condition[is.na(meta$condition)|meta$condition==""] <- "Unknown"
meta$compartment[is.na(meta$compartment)|meta$compartment==""] <- "Unknown"

if(toupper(subset_comp)!="ALL"){
  keep_samps <- rownames(meta)[meta$compartment==subset_comp]
  if(length(keep_samps) < 3) stop(paste0("Subset '", subset_comp,"' has fewer than 3 samples."))
  meta   <- meta[keep_samps,,drop=FALSE]
  counts <- counts[, keep_samps, drop=FALSE]
}

# --- PCA ---
X <- t(scale(t(counts), center=TRUE, scale=TRUE)); X[!is.finite(X)] <- 0
pc <- prcomp(t(X), center=FALSE, scale.=FALSE)
var_pct <- round(summary(pc)$importance[2,1:2]*100, 1)

# --- export PC scores ---
pc_scores <- data.frame(sample=rownames(pc$x), pc$x[,1:5,drop=FALSE],
                        condition=meta$condition, compartment=meta$compartment,
                        row.names=NULL, check.names=FALSE)
out_prefix <- paste0(prefix, if(toupper(subset_comp)!="ALL") paste0("_", subset_comp) else "")
write.csv(pc_scores, file.path("results/tables", paste0(out_prefix, "_PCA_scores.csv")), row.names=FALSE)

# --- PCA figure (publication colors) ---
need(c("ggplot2","ggrepel"))
pdf(file.path(outdir, paste0(out_prefix, "_PCA_samples.pdf")), width=6.6, height=5.2)
if(requireNamespace("ggplot2", quietly=TRUE)){
  library(ggplot2)
  df <- data.frame(PC1=pc$x[,1], PC2=pc$x[,2],
                   condition=meta$condition, compartment=meta$compartment,
                   sample=rownames(pc$x))
  p <- ggplot(df, aes(PC1, PC2, color=condition, shape=compartment)) +
       geom_point(size=2.8, alpha=0.95) +
       scale_color_manual(values=okabe, drop=FALSE) +
       scale_shape_manual(values=c(Epithelial=16, Stromal=17, Unknown=15), drop=FALSE) +
       labs(title=paste0("PCA – ", out_prefix),
            x=paste0("PC1 (", var_pct[1], "%)"),
            y=paste0("PC2 (", var_pct[2], "%)"),
            color="Condition", shape="Compartment") +
       theme_minimal(base_size=12) +
       theme(plot.title=element_text(face="bold"),
             legend.position="right")
  if(requireNamespace("ggrepel", quietly=TRUE)){
    library(ggrepel)
    d <- sqrt((df$PC1-mean(df$PC1))^2 + (df$PC2-mean(df$PC2))^2)
    p <- p + ggrepel::geom_text_repel(
      data=df[order(d,decreasing=TRUE)[1:min(3,nrow(df))],],
      aes(label=sample), size=3)
  }
  print(p)
} else {
  col_map <- setNames(okabe[match(unique(meta$condition), names(okabe))], unique(meta$condition))
  pch_map <- c(Epithelial=16, Stromal=17, Unknown=15)
  plot(pc$x[,1], pc$x[,2],
       xlab=paste0("PC1 (", var_pct[1], "%)"),
       ylab=paste0("PC2 (", var_pct[2], "%)"),
       main=paste0("PCA – ", out_prefix),
       pch=pch_map[as.character(meta$compartment)],
       col=col_map[as.character(meta$condition)])
  legend("right", legend=names(col_map), col=col_map, pch=16, title="Condition", bty="n")
}
dev.off()

# --- Heatmap (guarantee these genes appear) ---
need("pheatmap")
must_genes <- c("CCR2","IL2RA","CXCL13","GZMK","TNFSF4")
rowvar <- apply(counts, 1, var, na.rm=TRUE)
top_by_var <- names(sort(rowvar, decreasing=TRUE))[seq_len(min(80, sum(is.finite(rowvar))))]

must_present <- intersect(must_genes, rownames(counts))
keep <- unique(c(must_present, top_by_var))
H <- counts[keep,,drop=FALSE]
H <- t(scale(t(H))); H[!is.finite(H)] <- 0

pdf(file.path(outdir, paste0(out_prefix, "_Heatmap_topVarGenes.pdf")), width=7.4, height=9)
if(requireNamespace("pheatmap", quietly=TRUE)){
  library(pheatmap)
  ann <- data.frame(Condition=meta$condition, Compartment=meta$compartment)
  rownames(ann) <- rownames(meta)
  col_fun <- colorRampPalette(c("#313695","#4575b4","#74add1","#abd9e9","#e0f3f8","#ffffbf",
                                "#fee090","#fdae61","#f46d43","#d73027","#a50026"))
  # Row annotation to mark the must-show genes
  row_ann <- data.frame(Marker=ifelse(rownames(H) %in% must_present, "★", ""))
  rownames(row_ann) <- rownames(H)

  pheatmap(H,
           color=col_fun(255),
           annotation_col=ann,
           annotation_row=row_ann,
           show_rownames=TRUE, show_colnames=TRUE,
           fontsize_row=6.5, fontsize_col=9,
           border_color=NA, clustering_method="complete",
           main=paste0("Top variable genes (scaled) – ", out_prefix))
} else {
  heatmap(H, Colv=TRUE, scale="none", margins=c(6,6), main=paste0("Top variable genes – ", out_prefix))
}
dev.off()

# --- run log ---
logf <- file.path(outdir, paste0(out_prefix, "_runlog.txt"))
sink(logf)
cat("Counts:", counts_path, "\n")
cat("Samples:", ncol(counts), " Genes:", nrow(counts), "\n")
cat("Subset compartment:", subset_comp, "\n")
print(table(meta$condition, useNA="ifany"))
print(table(meta$compartment, useNA="ifany"))
sink()